name: x_storage

environment:
  sdk: ">=3.6.0 <4.0.0"
dev_dependencies:
  melos: ^6.2.0
  # go_router_builder: ^2.3.0
  # build_runner: ^2.4.14
  # freezed: ^2.3.2
  # json_serializable: ^6.6.1
  # extender_dart_builder:
  # injectable_generator: ^2.6.2

# workspace:
#   - packages/x_storage_core
#   - packages/x_storage_flutter
#   - packages/x_storage_firebase
#   - packages/x_storage_wasabi
