name: x_storage_flutter
description: Flutter widgets for XStorage
version: 0.2.0
homepage: https://github.com/soraef/x_storage

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  x_storage_core: ^0.2.1
  just_audio: ^0.9.36
  cross_file: ^0.3.3+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
